### ISSUE TITLE
STR type is missing in Z80disassembler

### ISSUE THREAD

**Issue by HenniePeters** [sarnau/Z80DisAssembler#1]
Hello Markus,   
  
I would like to give Z80disassembler a try but a custom type STR is missing. I guess that I need SigmaStr but I cannot find it in either of your repositories.   
  
thanks,  
Hennie

**Comment by HenniePeters** [comment]
I got it working, but I had to add a few lines:
#define STR  char*
#define CHAR char
Also some constants had to be written in a different case
Boolean -> BOOLEAN, 
true -> TRUE, 
false -> FALSE
void main -> int main

**Comment by sarnau** [comment]
Fixed it
