### ISSUE TITLE
Probable hidden bug in z80_compile.c.

### ISSUE THREAD

**Issue by RockBrentwood** [sarnau/Z80DisAssembler#10]
In the current commit:
Line 802 of z80_compile.c

} else if((op1 == 0x630)||(op1 = 0x631)) {  // (IX+d), (IY+d)

should probably be:

} else if((op1 == 0x630)||(op1 == 0x631)) {  // (IX+d), (IY+d)

**Comment by sarnau** [comment]
Ehm, yes.

**Comment by sarnau** [comment]
Fixed

**Comment by sarnau** [comment]
https://github.com/sarnau/Z80DisAssembler/commit/1020fb0e45e5758bf916208b418e3288d9f6dbff
