### ISSUE TITLE
Some errors in the disassembler

### ISSUE THREAD

**Issue by HenniePeters** [sarnau/Z80DisAssembler#2]
Markus, I don't know if you are still maintaining this repository but I found a few errors:
40    HALT should be: LD B,B 
49    HALT should be: LD C,C
52    HALT should be: LD D,D
64    HALT should be: LD H,H
6D    HALT should be: LD L,L
76    HALT (this one is correct)
7F    HALT should be: LD A,A
ED 03 HALT (2 bytes instruction)

**Comment by Ho-Ro** [comment]
Also `$5b` is wrong, should be `ld e, e`.
Only `ld (hl), (hl)` is replaced by `halt`.
My fix for https://github.com/sarnau/Z80DisAssembler/blob/be8c312bc21af0c4b1dd9ed8706499a2edf7851c/z80_disassembler.c#L478-L487:
```c
    case 0x40:                          // LD   d,s
        if(a == 0x76) {
            strcpy(s,"HALT");
        } else {
            strcpy(s,"LD\t");
            strcat(s,reg[d]);
            strcat(s,",");
            strcat(s,reg[e]);
        }
        break;
```

**Comment by sarnau** [comment]
Totally missed you comment. Yes, obviously the 0x76 HALT was wrong, triggering the other issues. This should now be fixed.
