### ISSUE TITLE
Suggestion for a fix for the disassembler.

### ISSUE THREAD

**Issue by RockBrentwood** [sarnau/Z80DisAssembler#9]
Using the routine

void Generate(char *S, const char *Format, ...) {
   va_list AP; va_start(AP, Format), vsprintf(S, Format, AP), va_end(AP);
}

with the include

#include <stdarg.h>

will allow you to clean up and compact the source code, with a dramatic increase in clarity.

Example: Your
            case 0x04:
                strcpy(s,"LD      (");
                snprintf(stemp,sizeof(stemp),"%4.4Xh",Opcodes[adr+1]+(Opcodes[adr+2]<<8));strcat(s,stemp);
                strcat(s,"),HL");
                break;
(currently on and after line 385 in your "z80_disassembler.cp" file) becomes
            case 0x04: Generate(s,"LD      (%4.4Xh),HL",Opcodes[adr+1]+(Opcodes[adr+2]<<8)); break;
With this, there is no longer any need for "stemp".

In addition, using octal for the opcodes will make everything more transparent. In fact you're already parsing octal digits for each opcode and your jump table is already set up that way.

My local version of your disassembler is down to about 450 lines - with a few corrections made in the opcode table. (You'll see gaps and inconsistencies more readily once the changes have been made.) I might fork a public-facing version and put up the revisions later, time permitting, once things are stabilized on your end.

The following may be used for reference:
https://www.pastraiser.com/cpu/Z80/Z80_opcodes.html
https://jnz.dk/z80/opref.html

I have a cleaned-up version of them both, locally, which formats everything on an octal-basis, which I might also add to the public-facing fork. Any revisions I make in my version, when they become available, you're free to use.

**Comment by Ho-Ro** [comment]
Hi @RockBrentwood - It looks like the Z80 is not yet dead :) I'm also working on Markus' asm and dis code. If you're interested in my "frontend" with arg parsing and using different input file formats beside pure binary (e.g intel hex as well as the *.z80 format, a binary with header for the code offset) you could have a look at [my devel branch](https://github.com/Ho-Ro/Z80DisAssembler/tree/devel).
Thx for the opcode lists, I would like to add two other info sources that I use quite often:

- [Z80 Opcode Table](https://clrhome.org/table/)
- [the-2-3-3-opcode-bit-pattern](https://floooh.github.io/2021/12/06/z80-instruction-timing.html#the-2-3-3-opcode-bit-pattern)

In early CP/M and Z80 days, I used my quick-hacked octal group-based disasm (coded in Pascal), so the `z80_disassembler` approach looked familiar. I use also the `z80_assembler` b/c it's straight forward and extensible w/o a lot of weird (at least for me) flex/bison stuff. I've added command line arguments and various output file formats there too.

**Comment by sarnau** [comment]
I've added the change – slightly different, but in the same way to make the code much easier to read.

**Comment by sarnau** [comment]
https://github.com/sarnau/Z80DisAssembler/commit/09b2a7c12aa0c09cc0b2ccea4faca8f1195aff21

**Comment by RockBrentwood** [comment]
I'll take the counter-suggestion, regarding sprintf, under advisement, on my end. I expected that once you made the revisions, other things would come more clearly into view, leading to additional changes, some of which have already taken place. So, I'll wait a while longer for things to stabilize before adding a public-facing fork.

With the present design, it should not be very difficult to generalize the disassembler to the 8080 and 8085 ... and even to the 8086/8088, whose opcode binary format has a similar layout.

A few more links you might be interested in:
I reanimated, and updated to C99 compatibility, the Frankenstein assembler: https://github.com/RockBrentwood/CPU/tree/main/assemblers/Frankasm
It has files for many CPU's, including the Z80 and Z180.

The ASL assembler has also been cleaned up and updated (and repaired): https://github.com/RockBrentwood/CPU/tree/main/assemblers/asl-1.41r6
It supports about 50 CPU's, including the Z80.

There may be items in there that you will find to be of use.

Also, if the output of your disassembler is made into legal assembly language, then it will be possible to cross-test it against your assembler.

Edit (2024-10-03): I put my copy of the opcode tables, octal-formatted with X's, Y's, Z's, on my fork. It's subject to change and update to include the unofficial opcodes and maybe also the Z180 cases.
